function C = coriolis_matrix(in1)
%CORIOLIS_MATRIX
%    C = CORIOLIS_MATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    28-Dec-2015 17:34:34

hipJL = in1(30,:);
hipJR = in1(36,:);
hipPL = in1(28,:);
hipRL = in1(29,:);
hipPR = in1(34,:);
hipRR = in1(35,:);
hipJLd = in1(12,:);
hipJRd = in1(18,:);
hipPLd = in1(10,:);
hipRLd = in1(11,:);
hipPRd = in1(16,:);
hipRRd = in1(17,:);
kneeL = in1(27,:);
kneeR = in1(33,:);
kneeLd = in1(9,:);
kneeRd = in1(15,:);
rootJ = in1(24,:);
rootP = in1(22,:);
rootR = in1(23,:);
rootJd = in1(6,:);
rootPd = in1(4,:);
rootRd = in1(5,:);
