function G = gravity_matrix(in1)
%GRAVITY_MATRIX
%    G = GRAVITY_MATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    28-Dec-2015 15:02:21

anklePL = in1(15,:);
ankleRL = in1(16,:);
hipPL = in1(18,:);
hipRL = in1(19,:);
hipPR = in1(20,:);
hipRR = in1(21,:);
kneeL = in1(17,:);
kneeR = in1(22,:);
G = [0.0;0.0;-3.0;sin(anklePL+kneeL).*cos(ankleRL).*(7.0./1.0e1)+cos(ankleRL).*sin(anklePL).*(2.7e1./2.5e1);cos(kneeL).*sin(ankleRL).*(1.0./5.0)+cos(anklePL+kneeL).*sin(ankleRL).*(7.0./1.0e1)+sin(ankleRL+hipPL).*cos(hipRL).*(1.0./1.0e1)+cos(anklePL).*sin(ankleRL).*(2.7e1./2.5e1);cos(ankleRL).*sin(kneeL).*(1.0./5.0)+sin(anklePL+kneeL).*cos(ankleRL).*(7.0./1.0e1);sin(ankleRL+hipPL).*cos(hipRL).*(1.0./1.0e1);sin(hipRL+hipRR+kneeR).*cos(hipPR).*(-1.0./1.0e1)+cos(ankleRL+hipPL).*sin(hipRL).*(1.0./1.0e1);cos(hipRR).*sin(hipPR).*(-1.0./5.0)-sin(hipPR).*cos(hipRL+hipRR+kneeR).*(1.0./1.0e1);cos(hipPR).*sin(hipRR).*(-1.0./5.0)-cos(kneeR).*sin(hipRR).*(1.0./1.0e1)-sin(hipRL+hipRR+kneeR).*cos(hipPR).*(1.0./1.0e1);cos(hipRR).*sin(kneeR).*(-1.0./1.0e1)-sin(hipRL+hipRR+kneeR).*cos(hipPR).*(1.0./1.0e1)];
